[EDIT] trying to exit if there is an annotation

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,9 +22,15 @@ jobs:
       - run: echo ${GITHUB_REF}
       - run: check.sh $(pwd) $(pwd)
       - run: cat coding-style-reports.log
-      - run: |
-        grep -n coding-style-reports.log
       - run: echo ::error file=coding-style-reports.log,line=1,endLine=10,title=MAJOR/MINOR coding style error::error reference
+      - run: |
+          if [ -s "coding-style-reports.log" ]; then
+            cat coding-style-reports.log | grep -v '^$' | while read line ; do echo "::error:: $line" ; done
+          fi
+      - run: |
+          if [ -s "coding-style-reports.log" ]; then
+            exit 1 ; done
+          fi
 
   check_program_compilation:
     needs: check_coding_style
